name: CI
on: [push, workflow_dispatch]
jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - run: go test ./...
